# Generated by Django 5.2.4 on 2025-08-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techinicien', '0002_questiondiagnostic_choixreponse_reglediagnostic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsediagnostic',
            name='choix_selectionnes',
        ),
        migrations.CreateModel(
            name='ChoixSelectionne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selection', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='Techinicien.choixreponse')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_selectionnes_list', to='Techinicien.reponsediagnostic')),
            ],
            options={
                'verbose_name': 'Choix sélectionné',
                'verbose_name_plural': 'Choix sélectionnés',
                'unique_together': {('reponse', 'choix')},
            },
        ),
    ]
