# Generated by Django 5.2.4 on 2025-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techinicien', '0003_remove_reponsediagnostic_choix_selectionnes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondiagnostic',
            name='recommandations',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
